version: '3.8'

services:
  tle-http:
    build: .
    container_name: tle-forwarder-http
    ports:
      - "8000:8000"
    command: ./tle-forwarder
    restart: unless-stopped

  tle-coap:
    build: .
    container_name: tle-forwarder-coap
    ports:
      - "5683:5683/udp"
    command: ./tle-forwarder-coap
    restart: unless-stopped
